apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service-app
  template:
    metadata:
      labels:
        app: api-gateway-service-app
    spec:
      containers:
      - name: api-gateway-service-app
        image: sagarpatiljava/api-gateway:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9191
---

kind: Service
apiVersion: v1
metadata:
  name: api-gateway-service-svc
spec:
  selector:
    app: api-gateway-service-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9191
    protocol: TCP