apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-app
  labels:
    app: booking-service-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: booking-service-app
  template:
    metadata:
      labels:
        editor: booking-service-app
    spec:
      containers:
      - name: booking-service-app
        image: sagarpatiljava/booking-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
kind: Service
apiVersion: v1
metadata:
  name:  booking-service-svc
spec:
  selector:
    app:  booking-service-app
  type:  ClusterIP
  ports:
  - port:  80
    targetPort:  8080