apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        editor: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: sagarpatiljava/user-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
kind: Service
apiVersion: v1
metadata:
  name:  user-service-svc
spec:
  selector:
    app:  user-service-app
  type:  ClusterIP
  ports:
  - port:  80
    targetPort:  8081